### ISSUE TITLE
Support history_mode with additional_cycles

### ISSUE THREAD

**Issue by elric1** [oxheadalpha/tezos-k8s#324]
The syntax for specifying the number of cycles to preserve before the current cycle in history mode is "rolling:N".

**Comment by elric1** [comment]
Hmmm, apparently, the `:N` is supported on the command line, but not in the config file.

**Comment by elric1** [comment]
I asked around, the syntax would be something like this:
```
config:
  shell:
    history_mode:
      rolling:
        additional_cyles: 7
```
This will break the scripts in different ways, so let me adjust the name of this issue to compensate.
