### ISSUE TITLE
Helm: Should be able to set certain values in values.yaml to null instead of {}

### ISSUE THREAD

**Issue by harryttd** [oxheadalpha/tezos-k8s#443]
For example:
```yaml
# This would be an attempt to not create any nodes via a specifying it in a secondary values file.
# It wouldn't work bec the nodes section of the chart's default values.yaml file will get merged into
# it, creating a rolling node.
nodes: {}

# let this work instead to not create any nodes:
nodes: null
```
A use case would be wanting to only deploy a remote signer.

Resolving this issue will require updates in config generator, with possibly needing other updates as well.  For example:
```python
NODES = json.loads(os.environ["NODES"])
```
The above will fail bec it is expecting a dict for the NODES env var.
